version: '3.8'

services:
  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=https://api.${DOMAIN}
    networks:
      - app-network

  api:
    build: ./job-listings-api
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - SCRAPER_SCHEDULE=*/60  # Run scraper every 60 minutes
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN
      - API_DOMAIN=api.${DOMAIN}
    command: |
      caddy reverse-proxy \
        --from $$DOMAIN \
        --to frontend:80 \
        --from $$API_DOMAIN \
        --to api:8000
    networks:
      - app-network

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  app-network: