FROM python:3.12-slim

WORKDIR /app

RUN pip install poetry

COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

COPY . .

# Default command is overridden in docker-compose.yaml
CMD ["poetry", "run", "celery", "-A", "src.services.tasks", "worker", "--loglevel=info"]
